name = "wish-factory"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables for production
[env.production.vars]
PUBLIC_SUPABASE_URL = "https://bnbzkfwowcqnecrdqdas.supabase.co"

# Environment variables for development  
[env.preview.vars]
PUBLIC_SUPABASE_URL = "https://kgowrcgwzqfeiqitavdc.supabase.co"