// Generated by Supabase CLI - will be replaced when database is set up
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			wishes: {
				Row: {
					id: string;
					type: 'normal' | 'herzlich' | 'humorvoll';
					event_type: 'birthday' | 'anniversary' | 'custom';
					relations: string[];
					age_groups: string[];
					specific_values: number[];
					text: string;
					belated: boolean;
					status: 'Entwurf' | 'Zur Freigabe' | 'Freigegeben' | 'Archiviert';
					language: 'de' | 'en';
					created_at: string;
					updated_at: string;
					created_by: string;
				};
				Insert: {
					id?: string;
					type: 'normal' | 'herzlich' | 'humorvoll';
					event_type: 'birthday' | 'anniversary' | 'custom';
					relations: string[];
					age_groups: string[];
					specific_values?: number[];
					text: string;
					belated: boolean;
					status?: 'Entwurf' | 'Zur Freigabe' | 'Freigegeben' | 'Archiviert';
					language: 'de' | 'en';
					created_at?: string;
					updated_at?: string;
					created_by: string;
				};
				Update: {
					id?: string;
					type?: 'normal' | 'herzlich' | 'humorvoll';
					event_type?: 'birthday' | 'anniversary' | 'custom';
					relations?: string[];
					age_groups?: string[];
					specific_values?: number[];
					text?: string;
					belated?: boolean;
					status?: 'Entwurf' | 'Zur Freigabe' | 'Freigegeben' | 'Archiviert';
					language?: 'de' | 'en';
					created_at?: string;
					updated_at?: string;
					created_by?: string;
				};
			};
			profiles: {
				Row: {
					id: string;
					role: 'Redakteur' | 'Administrator';
					email: string;
					full_name: string;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					role?: 'Redakteur' | 'Administrator';
					email: string;
					full_name: string;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					role?: 'Redakteur' | 'Administrator';
					email?: string;
					full_name?: string;
					created_at?: string;
					updated_at?: string;
				};
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			wish_type: 'normal' | 'herzlich' | 'humorvoll';
			event_type: 'birthday' | 'anniversary' | 'custom';
			wish_status: 'Entwurf' | 'Zur Freigabe' | 'Freigegeben' | 'Archiviert';
			language: 'de' | 'en';
			user_role: 'Redakteur' | 'Administrator';
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
}
