name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate i18n files
        run: npx paraglide-js compile

      - name: Format generated files
        run: npm run format

      - name: Run type checking
        run: npm run check

      - name: Run linting
        run: npm run lint

      - name: Setup Development Environment
        if: github.ref == 'refs/heads/develop'
        run: |
          cp .env.development .env
          echo "Using Development Supabase (current instance)"

      - name: Setup Production Environment
        if: github.ref == 'refs/heads/main'
        run: |
          cp .env.production .env
          # Override with GitHub Secrets for Production
          echo "PUBLIC_SUPABASE_URL=${{ secrets.PROD_SUPABASE_URL }}" >> .env
          echo "PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PROD_SUPABASE_ANON_KEY }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.PROD_SUPABASE_SERVICE_ROLE_KEY }}" >> .env
          echo "Using Production Supabase (separate account)"

      - name: Build application
        run: npm run build

      - name: Deploy to Development
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 4e19556f50aaf4e6b2f8cdcdbb5df0eb
          command: pages deploy .svelte-kit/cloudflare --project-name=wish-factory-dev --branch=develop

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 4e19556f50aaf4e6b2f8cdcdbb5df0eb
          command: pages deploy .svelte-kit/cloudflare --project-name=wish-factory

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment will be available once merged to develop branch!'
            })
